```{r}
library(tidyverse)
library(viridis)
library(car)
library(ggpubr)
library(MASS)
```

```{r}
neomod <- read.table("../Data/neomod_isam12.dat", header = TRUE)

neomod$cns    = factor(neomod$cns)
neomod$size   = factor(neomod$size)
neomod$gest   = factor(neomod$gest)
neomod$emp.f  = factor(neomod$emp.f)
neomod$emp.m  = factor(neomod$emp.m)
neomod$edu    = factor(neomod$edu)
neomod$re.ad  = factor(neomod$re.ad)
neomod$sex    = factor(neomod$sex)
neomod$accom  = factor(neomod$accom)
```



```{r}
p.bwt <- neomod %>%
  ggplot(aes(x = re.ad, y = bwt, fill = re.ad)) +
    geom_violin() +
    scale_fill_viridis(discrete = TRUE, alpha = 0.6) +
    geom_jitter(color = "black", size = 0.4, alpha = 0.9) +
    theme(
      legend.position = "none",
      plot.title = element_text(size = 11)
    )
p.los <- neomod %>%
  ggplot(aes(x = re.ad, y = los, fill = re.ad)) +
    geom_violin() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    geom_jitter(color="black", size=0.4, alpha=0.9) +
    theme(
      legend.position = "none",
      plot.title = element_text(size = 11)
    )
ggarrange(p.bwt, p.los, ncol = 2, nrow = 1)
```

```{r}
mod.nolos.full <- glm(re.ad ~ . -los + cns:size + cns:gest + cns:bwt + cns:emp.f + 
                        cns:emp.m + cns:edu + cns:sex + size:gest + size:bwt + 
                        size:emp.f + size:emp.m + size:edu + size:sex + gest:bwt + 
                        gest:emp.f + gest:emp.m + gest:edu + gest:sex + bwt:emp.f + 
                        bwt:emp.m + bwt:edu + bwt:sex + emp.f:emp.m + emp.f:edu + 
                        emp.f:sex + emp.m:edu + emp.m:sex + edu:sex,
                        data = neomod,
                        family = binomial)

summary.glm(mod.nolos.full)
```

```{r}
mod.los.full <- glm(re.ad ~ . + cns:size + cns:gest + cns:bwt + cns:emp.f + cns:emp.m + 
                      cns:edu + cns:sex + size:gest + size:bwt + size:emp.f + size:emp.m + 
                      size:edu + size:sex + gest:bwt + gest:emp.f + gest:emp.m + gest:edu + 
                      gest:sex + bwt:emp.f + bwt:emp.m + bwt:edu + bwt:sex + emp.f:emp.m + 
                      emp.f:edu + emp.f:sex + emp.m:edu + emp.m:sex + edu:sex,
                      data = neomod,
                      family = binomial)

summary.glm(mod.los.full)
```

```{r}
f = anova(mod.los.full, mod.nolos.full, test = "Chisq")

f
```

```{r}
mod.binomial <- glm(re.ad ~ . + cns:emp.f + size:emp.f + size:emp.m + gest:edu + bwt:edu + emp.m:edu,
                data = neomod,
                family = binomial)

deviance(mod.binomial) / df.residual(mod.binomial)
```

```{r}
mod.quasibinomial <- glm(re.ad ~ . + cns:emp.f + size:emp.f + size:emp.m + gest:edu + bwt:edu + emp.m:edu,
                data = neomod,
                family = quasibinomial)

pchisq(summary(mod.binomial)$dispersion * mod.quasibinomial$df.residual, mod.quasibinomial$df.residual, lower = FALSE)
```

```{r}
mod.step <- stepAIC(mod.binomial, direction = "both", trace = FALSE)
mod.step
```

```{r}
anova(mod.step, mod.binomial, test = "Chisq")
```

```{r}
summary.glm(mod.step)
```

```{r, fig.align="center"}
par(mfrow = c(2,2), mar = c(2.5,2,2,1))
plot(mod.step)
```
